include: package:effective_dart/analysis_options.1.3.0.yaml

analyzer:
  exclude: ["**/*.freezed.dart", "**/*.config.dart", "**/*generated_plugin_registrant.dart", "**/*.gen.dart"]

linter:
  rules:
    public_member_api_docs: false
    avoid_classes_with_only_static_members: false
    avoid_print: true
    prefer_single_quotes: true
    avoid_positional_boolean_parameters: false