name: geldstroom
description: A new Flutter project.

publish_to: "none"

version: 0.4.3+21

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^2.5.0
  cupertino_icons: ^1.0.0
  dartz: ^0.9.2
  dio: ^3.0.10
  equatable: ^1.2.5
  flushbar: ^1.10.4
  flutter_bloc: ^6.1.1
  flutter_dotenv: ^2.1.0
  flutter_linkify: ^4.0.2
  flutter_screenutil: ^4.0.3+1
  flutter_slidable: ^0.5.7
  flutter_spinkit: ^4.1.2+1
  flutter_svg: ^0.19.0
  freezed_annotation: ^0.12.0
  get_it: ^5.0.1
  google_fonts: ^1.1.1
  hydrated_bloc: ^6.1.0
  injectable: ^1.0.5
  intl: ^0.16.1
  introduction_screen: ^1.0.9
  jiffy: ^3.0.1
  jwt_decoder: ^1.0.3
  meta: ^1.2.4
  modal_bottom_sheet: ^1.0.0+1
  package_info: ^0.4.3+2
  scrollable_positioned_list: ^0.1.8
  shared_preferences: ^0.5.12+4
  styled_widget: ^0.2.2
  url_launcher: ^5.7.10
  syncfusion_flutter_charts: ^18.4.41
  onesignal_flutter: ^2.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^0.2.9  
  bloc_test: ^7.1.0
  build_runner: ^1.10.6

  effective_dart: ^1.3.0
  flutter_gen: null

  flutter_launcher_icons: ^0.8.1
  freezed: ^0.12.3
  injectable_generator: ^1.0.6
  integration_test: ^1.0.0
  mockito: ^4.1.3
  network_image_mock: ^1.0.2

flutter:
  uses-material-design: true

  assets:
    - .dev.env
    - .env
    - assets/images/

flutter_gen:
  output: null
  lineLength: 80 # Optional (default: 80)

  integrations:
    flutter_svg: true

flutter_native_splash:
  image: assets/images/splash.png
  color: "0E1216"
  android_disable_fullscreen: true
