name: geldstroom
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_dotenv: ^2.1.0
  get_it: ^5.0.1
  google_fonts: ^1.1.1
  injectable: ^1.0.5
  shared_preferences: ^0.5.12+4
  styled_widget: ^0.2.2
  flutter_svg: ^0.19.0
  introduction_screen: ^1.0.9
  flutter_screenutil: ^4.0.0-beta

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.6

  effective_dart: ^1.3.0
  injectable_generator: ^1.0.6
  network_image_mock: ^1.0.2
  flutter_gen:

flutter:
  uses-material-design: true

  assets:
    - .dev.env
    - .env
    - assets/images/


flutter_gen:
  output: lib/constant/ # Optional (default: lib/gen/)
  lineLength: 80 # Optional (default: 80)

  integrations:
    flutter_svg: true
