name: geldstroom
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_dotenv: ^2.1.0
  get_it: ^5.0.1
  google_fonts: ^1.1.1
  injectable: ^1.0.5
  shared_preferences: ^0.5.12+4
  styled_widget: ^0.2.2
  flutter_svg: ^0.19.0
  introduction_screen: ^1.0.9
  flutter_screenutil: ^4.0.0-beta
  flutter_bloc: ^6.1.1
  freezed_annotation: ^0.12.0
  dio: ^3.0.10
  jwt_decoder: ^1.0.3
  equatable: ^1.2.5
  meta: ^1.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.6
  freezed: ^0.12.3
  flutter_gen:
  injectable_generator: ^1.0.6
  network_image_mock: ^1.0.2
  mockito: ^4.1.3
  bloc_test: ^7.1.0

  effective_dart: ^1.3.0
  
  flutter_launcher_icons: ^0.8.1
  flutter_native_splash: 
    git:
      url: https://github.com/henriquearthur/flutter_native_splash.git

flutter:
  uses-material-design: true

  assets:
    - .dev.env
    - .env
    - assets/images/


flutter_gen:
  output: lib/constant/ # Optional (default: lib/gen/)
  lineLength: 80 # Optional (default: 80)

  integrations:
    flutter_svg: true

flutter_native_splash:
  image: assets/images/splash.png
  color: "272121"