name: CD
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create env file
        uses: SpicyPizza/create-envfile@v1
        with:
          file_name: .env
          envkey_BASE_URL: ${{ secrets.BASE_URL }}
          envkey_SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          envkey_ONE_SIGNAL_ID: ${{ secrets.ONE_SIGNAL_ID }}
      - name: Create production env file
        uses: SpicyPizza/create-envfile@v1
        with:
          file_name: .env
          envkey_BASE_URL: ${{ secrets.BASE_URL }}
          envkey_SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          envkey_ONE_SIGNAL_ID: ${{ secrets.ONE_SIGNAL_ID }}

      - uses: subosito/flutter-action@v1
        with:
          channel: stable
      - name: Install Dependencies
        run: flutter pub get
      - name: Run Build Runner
        run: flutter packages pub run build_runner build --delete-conflicting-outputs
      - name: Analyze
        run: flutter analyze .
      - name: Build APK
        run: flutter build apk --dart-define mode=production

        # @TODO
        # 1. Build app bundle
        # 2. Publish to play store
