name: CD
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create service_account.json
        run: echo '${{ secrets.SERVICE_ACCOUNT_JSON }}' > service_account.json
      - name: Create Android Firebase Config JSON
        uses: narcodico/base64-to-path@v1
        with:
          filepath: ${{ github.workspace }}/android/app/google-services.json
          encodedString: ${{ secrets.GOOGLE_SERVICES_JSON_BASE_64}}
      - name: Create iOS Firebase Config plist
        uses: narcodico/base64-to-path@v1
        with:
          filepath: ${{ github.workspace }}/ios/Runner/GoogleService-Info.plist
          encodedString: ${{ secrets.GOOGLE_SERVICES_PLIST_BASE_64}}       
      - name: Create .env
        uses: narcodico/base64-to-path@v1
        with:
          filePath: ${{ github.workspace }}/.env
          encodedString: ${{ secrets.ENV_BASE64 }}
      - name: Create .dev.env
        uses: narcodico/base64-to-path@v1
        with:
          filePath: ${{ github.workspace }}/.dev.env
          encodedString: ${{ secrets.ENV_DEV_BASE64 }}
      - name: Create key.properties
        uses: narcodico/base64-to-path@v1
        with:
          filePath: ${{ github.workspace }}/android/key.properties
          encodedString: ${{ secrets.KEY_PROPERTIES }}
      - name: Create Signing Key
        uses: narcodico/base64-to-path@v1
        with:
          filePath: ${{ github.workspace }}/android/app/key.jks
          encodedString: ${{ secrets.SIGNING_KEY }}
      - uses: subosito/flutter-action@v1
        with:
          channel: stable
      - name: Install Dependencies
        run: flutter pub get
      - name: Run Build Runner
        run: flutter packages pub run build_runner build --delete-conflicting-outputs
      - name: Analyze
        run: flutter analyze .
      - name: Build App Bundle
        run: flutter build appbundle --dart-define mode=production
      - name: Publish to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          track: production
          whatsNewDirectory: distribution/whatsnew
          packageName: com.cotc.geldstroom
          serviceAccountJson: service_account.json
          releaseFiles: build/app/outputs/bundle/release/app-release.aab
          mappingFile: build/app/outputs/mapping/release/mapping.txt
