name: CI
on:
  push:
    branches:
      - dev
      - beta
    paths:
      - "lib/**"
      - "test/**"
      - ".github/workflows/ci.yaml"
  pull_request:
    branches:
      - dev 
      - beta

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create .env
        uses: narcodico/base64-to-path@v1
        with:
          filePath: ${{ github.workspace }}/.env
          encodedString: ${{ secrets.ENV_BASE64 }}
      - name: Create .dev.env
        uses: narcodico/base64-to-path@v1
        with:
          filePath: ${{ github.workspace }}/.dev.env
          encodedString: ${{ secrets.ENV_DEV_BASE64 }}
      - name: Create key.properties
        uses: narcodico/base64-to-path@v1
        with:
          filePath: ${{ github.workspace }}/android/key.properties
          encodedString: ${{ secrets.KEY_PROPERTIES }}
      - name: Create Signing Key
        uses: narcodico/base64-to-path@v1
        with:
          filePath: ${{ github.workspace }}/android/app/key.jks
          encodedString: ${{ secrets.SIGNING_KEY }}
      - uses: subosito/flutter-action@v1
        with:
          channel: stable
      - name: Install Dependencies
        run: flutter pub get
      - name: Run Build Runner
        run: flutter packages pub run build_runner build --delete-conflicting-outputs
      - name: Format
        run: flutter format --set-exit-if-changed .
      - name: Analyze
        run: flutter analyze .
      - name: Run tests
        run: flutter test --coverage lib
      - name: Check Code Coverage
        uses: VGVentures/very-good-coverage@v1.1.0
        with:
          path: ./coverage/lcov.info
          min_coverage: 50
          exclude: "**/*.freezed.dart **/*.config.dart  **/*.gen.dart **/*.appconfig.dart"
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Build APK
        run: flutter build apk --dart-define mode=dev
