name: CI
on: 
  push: 


jobs:     
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: stable
      - name: Create env file
      - uses: SpicyPizza/create-envfile@v1
      - with:
          file_name: .env
          envkey_BASE_URL: ${{ secrets.BASE_URL }} 
          envkey_SENTRY_DSN: ${{ secrets.SENTRY_DSN }}   
          envkey_ONE_SIGNAL_ID: ${{ secrets.ONE_SIGNAL_ID }}
      - name: Create dev env file
      - uses: SpicyPizza/create-envfile@v1
      - with:
          file_name: .dev.env
          envkey_BASE_URL: ${{ secrets.BASE_URL }} 
          envkey_SENTRY_DSN: ${{ secrets.SENTRY_DSN }}   
          envkey_ONE_SIGNAL_ID: ${{ secrets.ONE_SIGNAL_ID_DEV }}    
      - name: Install Dependencies
        run: flutter pub get
      - name: Run Build Runner
        run: flutter packages pub run build_runner build --delete-conflicting-outputs
      - name: Format
        run: flutter format --set-exit-if-changed .
      - name: Analyze
        run: flutter analyze .
      - name: Run tests
        run: flutter test --coverage
      - name: Check Code Coverage
        uses: VGVentures/very-good-coverage@v1.1.0
        with:
          path: ./coverage/lcov.info
          min_coverage: 50
          exclude: "**/*.freezed.dart **/*.config.dart **/*generated_plugin_registrant.dart **/*.gen.dart"
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Build APK
        run: flutter build apk --dart-define mode=production